/* global QUESTIONS */
const durationSeconds = 120 * 60;
const QUESTION_BANK = [...QUESTIONS];
const state = { current: 0, answers: {}, remaining: durationSeconds, interval: null, submitted: false, filter: 'all' };
const $ = (id) => document.getElementById(id);
const els = { welcome: $('welcome'), exam: $('exam'), results: $('results'), timer: $('timer'), questionText: $('questionText'), questionNumber: $('questionNumber'), options: $('options'), answerState: $('answerState'), nav: $('questionNav'), progress: $('progressBar'), progressText: $('progressText'), navCount: $('navCount'), prev: $('previousButton'), next: $('nextButton'), reviewList: $('reviewList'), quit: $('quitButton') };
const MOCK_LENGTH = Math.min(60, QUESTION_BANK.length);

function optionText(question, key) { return key ? `${key}. ${question.options[key]}` : 'No answer selected'; }
function answeredCount() { return Object.keys(state.answers).length; }
function renderTimer() { const h = String(Math.floor(state.remaining / 3600)).padStart(2, '0'); const m = String(Math.floor((state.remaining % 3600) / 60)).padStart(2, '0'); const s = String(state.remaining % 60).padStart(2, '0'); els.timer.textContent = `${h}:${m}:${s}`; els.timer.className = `timer${state.remaining <= 300 ? ' critical' : state.remaining <= 900 ? ' warning' : ''}`; }
function renderNavigation() { els.nav.innerHTML = QUESTIONS.map((_, index) => `<button type="button" class="nav-button ${state.answers[index] ? 'answered' : ''} ${index === state.current ? 'current' : ''}" data-index="${index}" aria-label="Go to question ${index + 1}">${index + 1}</button>`).join(''); els.nav.querySelectorAll('button').forEach(button => button.addEventListener('click', () => { state.current = Number(button.dataset.index); renderQuestion(); })); }
function renderProgress() { const count = answeredCount(); const text = `${count} of ${QUESTIONS.length} answered`; els.progress.style.width = `${(count / QUESTIONS.length) * 100}%`; els.progressText.textContent = text; els.navCount.textContent = `${count} / ${QUESTIONS.length}`; }
function renderQuestion() { const q = QUESTIONS[state.current]; els.questionNumber.textContent = `Question ${state.current + 1} of ${QUESTIONS.length}`; els.questionText.textContent = q.question; const selected = state.answers[state.current]; els.answerState.textContent = selected ? `Answer selected: ${selected}` : 'Not answered'; els.options.innerHTML = Object.entries(q.options).map(([key, text]) => `<label class="option ${selected === key ? 'selected' : ''}"><input type="radio" name="answer" value="${key}" ${selected === key ? 'checked' : ''}><span class="option-key">${key}</span><span class="option-text">${text}</span></label>`).join(''); els.options.querySelectorAll('input').forEach(input => input.addEventListener('change', () => { state.answers[state.current] = input.value; renderQuestion(); })); els.prev.disabled = state.current === 0; els.prev.style.visibility = state.current === 0 ? 'hidden' : 'visible'; els.next.textContent = state.current === QUESTIONS.length - 1 ? 'Review submission →' : 'Next question →'; els.next.onclick = () => { if (state.current < QUESTIONS.length - 1) { state.current++; renderQuestion(); } else submitPrompt(); }; renderNavigation(); renderProgress(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function selectMockQuestions() { const shuffled = [...QUESTION_BANK].sort(() => Math.random() - .5).slice(0, MOCK_LENGTH); QUESTIONS.splice(0, QUESTIONS.length, ...shuffled); }
function startExam() { selectMockQuestions(); els.welcome.classList.add('hidden'); els.exam.classList.remove('hidden'); renderTimer(); renderQuestion(); state.interval = setInterval(() => { state.remaining--; renderTimer(); if (state.remaining <= 0) submitExam(true); }, 1000); }
function submitPrompt() { const unanswered = QUESTIONS.length - answeredCount(); const message = unanswered ? `You have ${unanswered} unanswered question${unanswered === 1 ? '' : 's'}. Submit anyway?` : 'Ready to submit your exam?'; if (window.confirm(message)) submitExam(false); }
function submitExam(expired) { if (state.submitted) return; state.submitted = true; clearInterval(state.interval); els.exam.classList.add('hidden'); els.results.classList.remove('hidden'); const correct = QUESTIONS.filter((q, i) => state.answers[i] === q.answer).length; const unanswered = QUESTIONS.length - answeredCount(); const percent = Math.round((correct / QUESTIONS.length) * 100); const attempts = JSON.parse(localStorage.getItem('ccaf-attempts') || '[]'); attempts.unshift({ date: new Date().toISOString(), score: percent, correct, total: QUESTIONS.length, unanswered }); localStorage.setItem('ccaf-attempts', JSON.stringify(attempts.slice(0, 30))); $('scorePercent').textContent = `${percent}%`; $('scoreLine').textContent = `${correct} out of ${QUESTIONS.length} answers correct`; $('correctCount').textContent = correct; $('incorrectCount').textContent = answeredCount() - correct; $('unansweredCount').textContent = unanswered; $('scoreMessage').textContent = expired ? 'Time expired, so your attempt was submitted automatically.' : percent >= 80 ? 'Excellent work - you have a strong grasp of these concepts.' : percent >= 60 ? 'Good effort. Use the review below to reinforce the weaker areas.' : 'Use the detailed review below to turn this attempt into a stronger next one.'; renderReview(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function renderReview() { els.reviewList.innerHTML = QUESTIONS.map((q, index) => { const user = state.answers[index]; const correct = user === q.answer; const visible = state.filter === 'all' || (state.filter === 'correct' && correct) || (state.filter === 'incorrect' && !correct); return `<article class="review-card card ${correct ? 'correct' : 'incorrect'}" ${visible ? '' : 'hidden'}><div class="review-meta"><span>Question ${index + 1}</span><span class="badge ${correct ? 'correct' : 'incorrect'}">${correct ? 'Correct' : user ? 'Incorrect' : 'Unanswered'}</span></div><h3>${q.question}</h3><div class="answer-comparison"><div class="answer-box"><span>Your answer</span>${optionText(q, user)}</div><div class="answer-box actual"><span>Correct answer</span>${optionText(q, q.answer)}</div></div><p class="justification"><strong>Justification:</strong> ${q.justification}</p></article>`; }).join(''); }
function quitExam() { if (window.confirm('Quit this exam? Your progress will not be saved.')) window.location.reload(); }
$('beginButton').addEventListener('click', startExam); els.prev.addEventListener('click', () => { if (state.current) { state.current--; renderQuestion(); } }); $('submitButton').addEventListener('click', submitPrompt); els.quit.addEventListener('click', quitExam); document.querySelectorAll('.filter').forEach(button => button.addEventListener('click', () => { state.filter = button.dataset.filter; document.querySelectorAll('.filter').forEach(b => b.classList.toggle('active', b === button)); renderReview(); })); $('restartButton').addEventListener('click', () => window.location.reload()); $('questionCount').textContent = MOCK_LENGTH;
