/* Dashboard and practice mode. Data stays in the visitor's browser via localStorage. */
const portal = { practiceIndex: 0, practiceAnswers: {} };
const portalSections = ['welcome', 'exam', 'results', 'dashboard', 'practice'];
function showPortal(name) { portalSections.forEach(id => document.getElementById(id).classList.toggle('hidden', id !== name)); if (name === 'dashboard') renderDashboard(); if (name === 'practice') renderPractice(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function getCandidateStorageKey(name) { return `ccaf-attempts-${ name .trim() .toLowerCase() .replace(/\s+/g, "-") }`; } 
function attemptData(candidateName) { if (!candidateName) return []; return JSON.parse( localStorage.getItem( getCandidateStorageKey(candidateName) ) || "[]" ); } 
function allCandidates() { return JSON.parse( localStorage.getItem("ccaf-users") || "[]" ); }
function renderDashboard() { const selector = document.getElementById("candidateSelector"); const users = allCandidates(); selector.innerHTML = '<option value="">Select Candidate</option>'; users.forEach(user => { selector.innerHTML += `<option value="${user.name}"> ${user.name} </option>`; }); if (!selector.value && users.length) selector.value = users[0].name; const attempts = attemptData(selector.value); const stats = document.getElementById("dashboardStats"); const history = document.getElementById("attemptHistory"); if (!attempts.length) { stats.innerHTML = ` <article class="card dashboard-empty"> <h2>No attempts found</h2> <p> This candidate hasn't taken any exams. </p> </article> `; history.innerHTML = ""; return; } const average = Math.round( attempts.reduce( (sum, a) => sum + a.score, 0 ) / attempts.length ); const best = Math.max(...attempts.map(x => x.score)); const latest = attempts[0]; stats.innerHTML = ` <article class="stat-card card"> <span>Candidate</span> <strong>${selector.value}</strong> </article> <article class="stat-card card"> <span>Average</span> <strong>${average}%</strong> </article> <article class="stat-card card"> <span>Best</span> <strong>${best}%</strong> </article> <article class="stat-card card"> <span>Latest</span> <strong>${latest.score}%</strong> </article> <article class="stat-card card"> <span>Attempts</span> <strong>${attempts.length}</strong> </article> `; history.innerHTML = attempts.map(item => ` <div class="attempt-row"> <span> ${new Date(item.date).toLocaleDateString()} </span> <strong>${item.score}%</strong> <small> ${item.correct}/${item.total} Correct </small> </div> `).join(""); }
function renderPractice() { const q = QUESTION_BANK[portal.practiceIndex]; const answer = portal.practiceAnswers[portal.practiceIndex]; document.getElementById('practiceCount').textContent = `${QUESTION_BANK.length} questions available - no timer, instant feedback.`; document.getElementById('practicePosition').textContent = `Question ${portal.practiceIndex + 1} of ${QUESTION_BANK.length}`; document.getElementById('practicePrevious').disabled = portal.practiceIndex === 0; document.getElementById('practiceNext').disabled = portal.practiceIndex === QUESTION_BANK.length - 1; document.getElementById('practiceCard').innerHTML = `<div class="question-top"><span class="question-number">PRACTICE ${portal.practiceIndex + 1}</span><span class="answer-state">${answer ? 'Answered' : 'Choose an answer'}</span></div><h2>${q.question}</h2><div class="options">${Object.entries(q.options).map(([key, value]) => `<button class="practice-option ${answer === key ? 'selected' : ''} ${answer && key === q.answer ? 'practice-correct' : ''} ${answer && key === answer && key !== q.answer ? 'practice-wrong' : ''}" data-answer="${key}"><span class="option-key">${key}</span><span class="option-text">${value}</span></button>`).join('')}</div>${answer ? `<div class="practice-answer"><strong>Correct answer: ${q.answer}</strong><p>${q.justification}</p></div>` : ''}`; document.querySelectorAll('.practice-option').forEach(button => button.addEventListener('click', () => { portal.practiceAnswers[portal.practiceIndex] = button.dataset.answer; renderPractice(); })); }
document.querySelectorAll('[data-portal]').forEach(button => button.addEventListener('click', () => showPortal(button.dataset.portal)));
document.getElementById('practicePrevious').addEventListener('click', () => { portal.practiceIndex--; renderPractice(); });
document.getElementById('practiceNext').addEventListener('click', () => { portal.practiceIndex++; renderPractice(); });
const selector = document.getElementById("candidateSelector"); if (selector) { selector.addEventListener( "change", renderDashboard ); }
const resetButton = document.getElementById("resetCandidateHistory"); if (resetButton) { resetButton.addEventListener("click", () => { const selector = document.getElementById("candidateSelector"); if (!selector.value) return; if (!confirm( `Delete history for ${selector.value}?` )) return; localStorage.removeItem( getCandidateStorageKey(selector.value) ); renderDashboard(); }); }
