/* Dashboard and practice mode. Data stays in the visitor's browser via localStorage. */
const portal = { practiceIndex: 0, practiceAnswers: {} };
const portalSections = ['welcome', 'exam', 'results', 'dashboard', 'practice'];
function showPortal(name) { portalSections.forEach(id => document.getElementById(id).classList.toggle('hidden', id !== name)); if (name === 'dashboard') renderDashboard(); if (name === 'practice') renderPractice(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function attemptData() { return JSON.parse(localStorage.getItem('ccaf-attempts') || '[]'); }
function renderDashboard() { const attempts = attemptData(); const stats = document.getElementById('dashboardStats'); const history = document.getElementById('attemptHistory'); if (!attempts.length) { stats.innerHTML = `<article class="card dashboard-empty"><h2>No mock attempts yet</h2><p>Complete a timed mock to see your preparation trend and average score.</p><button class="button primary" data-portal="home">Go to mock exam</button></article>`; history.innerHTML = ''; stats.querySelector('button').addEventListener('click', () => showPortal('welcome')); return; } const average = Math.round(attempts.reduce((sum, item) => sum + item.score, 0) / attempts.length); const best = Math.max(...attempts.map(item => item.score)); const latest = attempts[0]; const status = average >= 80 ? 'Exam-ready momentum' : average >= 60 ? 'Solid progress - keep refining' : 'Build consistency with practice'; stats.innerHTML = `<article class="stat-card card"><span>Average score</span><strong>${average}%</strong><small>${status}</small></article><article class="stat-card card"><span>Best score</span><strong>${best}%</strong><small>Across ${attempts.length} attempt${attempts.length === 1 ? '' : 's'}</small></article><article class="stat-card card"><span>Latest attempt</span><strong>${latest.score}%</strong><small>${latest.correct}/${latest.total} correct</small></article>`; history.innerHTML = attempts.map((item, index) => `<div class="attempt-row"><span>Mock ${attempts.length - index}</span><span>${new Date(item.date).toLocaleDateString()}</span><strong>${item.score}%</strong><small>${item.correct}/${item.total} correct</small></div>`).join(''); }
function renderPractice() { const q = QUESTION_BANK[portal.practiceIndex]; const answer = portal.practiceAnswers[portal.practiceIndex]; document.getElementById('practiceCount').textContent = `${QUESTION_BANK.length} questions available - no timer, instant feedback.`; document.getElementById('practicePosition').textContent = `Question ${portal.practiceIndex + 1} of ${QUESTION_BANK.length}`; document.getElementById('practicePrevious').disabled = portal.practiceIndex === 0; document.getElementById('practiceNext').disabled = portal.practiceIndex === QUESTION_BANK.length - 1; document.getElementById('practiceCard').innerHTML = `<div class="question-top"><span class="question-number">PRACTICE ${portal.practiceIndex + 1}</span><span class="answer-state">${answer ? 'Answered' : 'Choose an answer'}</span></div><h2>${q.question}</h2><div class="options">${Object.entries(q.options).map(([key, value]) => `<button class="practice-option ${answer === key ? 'selected' : ''} ${answer && key === q.answer ? 'practice-correct' : ''} ${answer && key === answer && key !== q.answer ? 'practice-wrong' : ''}" data-answer="${key}"><span class="option-key">${key}</span><span class="option-text">${value}</span></button>`).join('')}</div>${answer ? `<div class="practice-answer"><strong>Correct answer: ${q.answer}</strong><p>${q.justification}</p></div>` : ''}`; document.querySelectorAll('.practice-option').forEach(button => button.addEventListener('click', () => { portal.practiceAnswers[portal.practiceIndex] = button.dataset.answer; renderPractice(); })); }
document.querySelectorAll('[data-portal]').forEach(button => button.addEventListener('click', () => showPortal(button.dataset.portal)));
document.getElementById('practicePrevious').addEventListener('click', () => { portal.practiceIndex--; renderPractice(); });
document.getElementById('practiceNext').addEventListener('click', () => { portal.practiceIndex++; renderPractice(); });
